[package]
name = "todoing"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
prettytable = "0.10"
chrono = { version = "0.4.41", features = ["serde"] }
serde_json = "1.0.140"
